### ISSUE TITLE
[SAM] Mangetsu/Oka AoE Combo Broken

### ISSUE THREAD

**Issue by Kylepetrucci** [attickdoor/XIVComboPlugin#108]
Mangetsu and Oka combos still try and start with Fuga instead of Fuko and do not work unless Meikyo Shisui is active

**Comment by Kylepetrucci** [comment]
with the 1.7.4 update, Mangetsu and Oka combos now properly and use Fuko for the starter, but Mangetsu and Oka are still only usable during Meikyo Shisui and not when using the combo normally.

**Comment by attickdoor** [comment]
fixed.

**Comment by Kylepetrucci** [comment]
Issue still occurs for me as described above on 1.7.5 on a lvl 90 SAM.  GIF below:

![WcEcycofBS](https://user-images.githubusercontent.com/3085100/145456912-e45931ff-3067-4754-9c20-a4af38e5b1a4.gif)

**Comment by Kylepetrucci** [comment]
This is now working properly in 1.7.8. Thank you!
