### ISSUE TITLE
Does not work well in 4K. Too small to see, or crops vital information. 

### ISSUE THREAD

**Issue by lovelydumpling** [attickdoor/XIVComboPlugin#64]
In 4K, at default scale the plugins menu are too tiny to see.
 
https://i.imgur.com/86F1Vkj.jpg

Dalamud has a setting to scale up the UI up to 2x, but in doing so, not everything fits in XIVCombos's window. Text overlapps and is cut off the screen, and more detrimentally the Save buttons are cropped off the bottom of the window. Scrolling down to the bottom does not reveal them.

https://i.imgur.com/dWHUYga.jpg

Other plugins let you click and drag the bottom right corner to resize/shape the plugin window, which lets everything fit. But many, including this one, do not. It'd be really helpful if this feature was added.

**Comment by attickdoor** [comment]
Wild. For some reason I didn't realize it was fixed size. This'll be fixed come October.

**Comment by ryankhart** [comment]
Ya, it's still an issue for me. I probably would have left the issue open so that people searching the issues with the default filters don't end up posting duplicate issues. IMO, the time to close an issue is when the fix is live and available to everyone.

I'm just happy that this issue will probably get addressed in the future, but I'm in no rush.

**Comment by lovelydumpling** [comment]
I'm sorry, yeah. I don't understand why this issue was closed, it is still a problem. The plugin has received several updates since then but this issue hasn't been fixed.

**Comment by lovelydumpling** [comment]
> Wild. For some reason I didn't realize it was fixed size. This'll be fixed come October.

Please re-open this issue, it was never fixed

**Comment by ryankhart** [comment]
Another alternative that could solve this problem in this plugin as well as all the other plugins that have a problem when you scale the font size in the Dalamud settings is if Dalamud settings had a UI scale instead of a font scale, so every fixed window sized plugin would be scaled with the fonts
